repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/golangci/golangci-lint
  rev: v1.41.1
  hooks:
  - id: golangci-lint
    name: golangci-lint
    description: Fast linters runner for Go.
    entry: golangci-lint run --fix
    types: [go]
    language: golang
    pass_filenames: false
- repo: https://github.com/TekWizely/pre-commit-golang
  rev: v1.0.0-beta.5
  hooks:
  - id: go-test-repo-mod
